apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: s3-benchmark-with-1m-data-
spec:
  entrypoint: dag
  templates:
  - name: kedro
    metadata:
      labels:
        app: kedro-argo
    retryStrategy:
      limit: 1
    inputs:
      parameters:
      - name: kedro_node
    container:
      imagePullPolicy: IfNotPresent
      image: s3-benchmark-with-1m-data
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: secret_access_key
        - name: AWS_DEFAULT_REGION
          value: us-west-1
      command: [kedro]
      args: ["run", "-n",  "{{inputs.parameters.kedro_node}}"]
  - name: dag
    dag:
      tasks:
      - name: outliers-node
        template: kedro
        arguments:
          parameters:
          - name: kedro_node
            value: outliers_node
      - name: create-target-node
        template: kedro
        dependencies:
          - outliers-node
        arguments:
          parameters:
          - name: kedro_node
            value: create_target_node
      - name: drop-cols-node
        template: kedro
        dependencies:
          - outliers-node
        arguments:
          parameters:
          - name: kedro_node
            value: drop_cols_node
      - name: fill-na-node
        template: kedro
        dependencies:
          - drop-cols-node
        arguments:
          parameters:
          - name: kedro_node
            value: fill_na_node
      - name: total-sf-node
        template: kedro
        dependencies:
          - drop-cols-node
        arguments:
          parameters:
          - name: kedro_node
            value: total_sf_node
